apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-http-backend
  labels:
    k8s-app: default-http-backend
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: default-http-backend
  template:
    metadata:
      labels:
        k8s-app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: default-http-backend
          # Any image is permissable as long as:
          # 1. It serves a 404 page at /
          # 2. It serves 200 on a /healthz endpoint
          image: registry.cn-shenzhen.aliyuncs.com/syzy-public/defaultbackend-amd64:1.5
          livenessProbe:
            httpGet:
              path: /healthz   #这个URI是 nginx-ingress-controller中nginx里配置好的localtion
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30   #30s检测一次/healthz
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
      #        resources:
      #          limits:
      #            cpu: 10m
      #            memory: 20Mi
      #          requests:
      #            cpu: 10m
      #            memory: 20Mi
---
apiVersion: v1
kind: Service     #为default backend 创建一个service
metadata:
  name: default-http-backend
  namespace: kube-system
  labels:
    k8s-app: default-http-backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    k8s-app: default-http-backend