apiVersion: v1
kind: PersistentVolume
metadata:
  name:  netdata
spec:
  capacity: 
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /netdata
    server: 172.30.250.45
